### ISSUE TITLE
In some places in the program, "Bookworm" is written with a lower case letter "b"

### ISSUE THREAD

**Issue by k-kolev1985** [mush42/bookworm#10]
## Describe the Problem

In some places in the program, the name of the program - "Bookworm" - is written with a lower case letter "B", instead of a capital one. I've noticed this in the "About" dialog and in the documentation as well.

I've fixed those cases in the bulgarian copy of the documentation. I cannot do it however in the "About" dialog, because the name of the program there is hard-coded as a variable. I'm referring to the "{name}" variable in the string "bookworm/gui/book_viewer/menubar/__init__.py:44".

## To Reproduce

1. Open Bookworm.
2. Open its "About" dialog".
3. Either press Control+C to copy the text content of the "About" dialog into the clipboard and paste it into a text editor and read it in there, or use your screen reader's method(s) of reading the text in the dialog directly from it.
4. Observe how the name of the program - "Bookworm" - positioned above the version number is written with a lower case "b", instead of a capital one.
5. Open Bookworm's documentation.
6. Search for "bookworm", writing it all in lower case and instructing the searching function to take upper/lower case in consideration when searching.

## Expected behavior

The name of the program in the text in the dialog box (above the version number) is written with a lower case "b", instead with a capital one. There are such instances of the program's name written in all lower case in the program's documentation as well.

## Desktop (please complete the following information):

 - Operating system: Windows 10 Pro version 1903 (build 18362.329), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version: 0.1b2, x86 (32-bit).

**Comment by k-kolev1985** [comment]
Yes, the test build that you've provided in #6 solves this issue. Thanks!

**Comment by mush42** [comment]
Hi @k-kolev1985,

You've done a great job today. I'm really indebted to you for taking it upon yourself to make this program better.

We really need more beta testers right now, so that we can release a stable version as soon as possible.

With my work and academic obligations, it is getting very hard to hunt bugs and develop features simultaneously. If some people took the burden of bugs hunting, I'll have more time focusing on the most important areas. I think this what open source is all about.

Thanks very much. And keep up the great work!
