### ISSUE TITLE
A search for a very long string brakes the search

### ISSUE THREAD

**Issue by k-kolev1985** [mush42/bookworm#19]
## Describe the Problem

A search for a very long string brakes the search - the searched string cannot be found, even if it exists in the book. I don't know how long the string has to be, but a bit longer sentence should do the job.

## To Reproduce

1. Open a book in Bookworm.
2. Open the "Search" dialog of Bookworm (press Ctrl+F).
3. Search for a particularly long string that you know it exists in the opened book.

## Expected behavior

Bookworm should find the searched string, but it does not - it reports that there are 0 results found.

## The File You've Opened

Most of my e-books are in EPUB format and that is in what format I'm searching for the long string. But I don't think the format matters. I even tried books with cyrillic and books with latin characters, but the result was the same.

## Desktop (please complete the following information):

 - Operating system: Windows 10 Pro version 1903 (build 18362.356), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version: 0.1b3, x86 (32-bit).

**Comment by mush42** [comment]
I expect this is caused by omitting line breaks. Let me investigate this issue further.

**Comment by mush42** [comment]
Well, the issue is not caused by searching for multi line strings, as we're using a single-line edit control that strips any lines after the first line.
The issue, in fact, happens because we search for a match in the raw page text, not the processed text. This makes it impossible to search for a whole paragraph, because that paragraph is represented, in the raw text, as a text block consisting of multiple lines.

I hope this fixes the issue. If not, we'll re-open it.
