### ISSUE TITLE
bookworm fails to start 

### ISSUE THREAD

**Issue by wilsonad32** [mush42/bookworm#5]
after using bookworm for several days, perhaps, 5 days, now it can't run. When i press enter on 'bookworm', nothing happen. I try uninstall and reinstall again, still the same. Curious why it fails to open.

**Comment by mush42** [comment]
Hi,
To properly diagnose the cause of this issue, we need two things:
1. Your system information
2. The logs.
Please compress Bookworm's logs folder as a zip file and attach it to your issue.
Bookworm's logs could  be found under the directory:
C:\Users\YOUR USER NAME\AppData\Roaming\Bookworm\logs

Regards,

**Comment by wilsonad32** [comment]
What system info is needed? btw, I'm using windows 10 home single language, intel core i5 processor, 
[log.zip](https://github.com/mush42/bookworm/files/3579464/log.zip)

**Comment by mush42** [comment]
Hi @wilsonad32 ,

Thanks for taking the initiative and reporting the issue.
The logs you've attached don't contain that much information. But this is understandable, since the app couldn't even boot up its subsystems.

To know whats actually happening under-the-hood, I've created a debug build for you. There is a high chance that if you've a problem with the latest version, it will continue to occur with this build as well. But this build logs more info about the workings of Bookworm than the one you already have.

Please follow these steps:
* Uninstall the version you have, restart your system, and install this one
* Run Bookworm as you would normally do
* Follow the instructions in my previous comment to bundle the new logs and attach them to your comment

The debug build is attached to this comment. Extract the file and run the installer.

[Bookworm-0.1b2-x86-debug-20190905setup.zip](https://github.com/mush42/bookworm/files/3580401/Bookworm-0.1b2-x86-debug-20190905setup.zip)

Regards,

**Comment by wilsonad32** [comment]
[log 2.zip](https://github.com/mush42/bookworm/files/3581978/log.2.zip)

**Comment by mush42** [comment]
Hi,

Your issue has been fixed. Thanks for making Bookworm better.

The fix will be shipped in a critical update which will be released within a week or so.

In the mean time, you could try removing Bookworm's configuration folder:
C:\Users\YOUR USER NAME\AppData\Roaming\Bookworm
This is  expected to resolve your issue.

Best Regards,
